### ISSUE TITLE
Not an issue: Project file?

### ISSUE THREAD

**Issue by briochemc** [ctkelley/NotebookSIAMFANL#6]
Hi Tim,

I just wanted to let you know that I was having a blast playing with the package/notebooks and share an idea that you might want to explore. I [forked](https://github.com/briochemc/NotebookSIAMFANL) NotebookSIAMFANL with minor changes so that I could add NotebookSIAMFANL directly with Pkg (in particular I added a Project file with *some* dependencies and removed PyPlot), and used that in a Pluto notebook (I really enjoy Pluto's reactive framework). Anyway, here is a quick example of what this allows for. I was curious about what happens when changing the starting `x0` in Chapter 1's first example, and so I built [this tiny Pluto notebook](https://gist.github.com/briochemc/7bb763bb64a9639d34ad7c5136356106#file-gif_notebooksiamfanl_pluto_ex1-jl) to simply have a slider set `x0` and move it around with the mouse:

![gif_notebookSIAMFANL](https://user-images.githubusercontent.com/4486578/116495523-64156400-a8e6-11eb-8c98-db3f5c52cd90.gif)

(You can copy-paste the notebook URL directly in Pluto and it should work since the whole environment is in the first cell of the notebook.)

I don't want to disturb your plans for your book, but maybe it's worth adding a Project file here so that one can directly use it as a package? (Not sure that's the best way forward, I'm perfectly fine with using my fork! 😄) 

Anyway, thanks again for the great package and notebooks!

Cheers,
Benoit

**Comment by ctkelley** [comment]
I thought of making the notebook its own package and may still do that. The problem is that most people in my community use notebooks by cloning the repo and putting it where they want. Making it a package means that it winds up in .julia/packages where it is hard for a novice to find. 

I had a Project.toml in an earlier version and it got in the way, so I put ```include("fanote_init.jl")``` in the first code cell to load the things one needs to load while running the notebook. The idea is that a novice can simply run the notebooks and play with the methods in code cells. 

Your Pluto example is cool. I am like IJulia better for this project because I understand the notebook-->print book map better and know how to get a bib in there.

**Comment by briochemc** [comment]
Maybe I'm just alone in this but I find this so cool I had to share another little screen recording:

https://user-images.githubusercontent.com/4486578/116642457-4ad9e980-a9b2-11eb-9b6d-922ec74371e2.mov

**Comment by ctkelley** [comment]
I'm glad you're having fun with this. Pluto seems to be much better for movies that IJulia, where it's a pain, as least for me. Please let me know if you find bugs in the solvers as you play with the notebook.
